// Generated by fde-demo ingest-api.ts — do not edit by hand.
// Mock-first: NEXT_PUBLIC_API_BASE unset -> /api/mock (serves data/mock-data.json).
const BASE = process.env.NEXT_PUBLIC_API_BASE ?? '/api/mock'

async function request(method: string, path: string) {
  const res = await fetch(BASE + path, { method, headers: { accept: 'application/json' } })
  if (!res.ok) throw new Error(`${method} ${path} -> ${res.status}`)
  return res.json()
}

/** 报修单列表 */
export async function listRepairOrders() {
  return request('GET', `/repair-orders`)
}

/** 报修单详情 */
export async function getRepairOrder(id: string | number) {
  return request('GET', `/repair-orders/${id}`)
}

/** 工程师名录（含区域与在修数） */
export async function listEngineers() {
  return request('GET', `/engineers`)
}
